### PR TITLE
Cd xtext issue 2849

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Archive screenshots in case of failure and increased SWTBot timeout

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
@cdietrich I added the changes on top of your branch concerning only the flaky job and the flaky SWTBot tests.
GitHub Actions don't start on my fork, so I'll have to check it in this PR

**Comment by LorenzoBettini** [comment]
The failed build is not related to this PR

**Comment by LorenzoBettini** [comment]
@cdietrich my timeout property does not work because in these projects you use SWTBot API with explicit fixed timeouts... I can fix that at least for deleteAllProjects, but in general it's an antipattern to use fixed timeouts when calling SWTBot API, at least for my knowledge

**Comment by cdietrich** [comment]
@LorenzoBettini can you please rebase on master

**Comment by cdietrich** [comment]
2nd question: dont you have write access to this repo?

**Comment by LorenzoBettini** [comment]
No I don't

**Comment by cdietrich** [comment]
@LorenzoBettini now you should

**Comment by cdietrich** [comment]
@LorenzoBettini yes PR against master

**Comment by LorenzoBettini** [comment]
Replaced by #391 https://github.com/xtext/xtext-reference-projects/pull/391

**Pull request closed without merging**
