### PR TITLE
regen examples

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Review by LorenzoBettini — COMMENTED** [review]
I think the domainmodel should have commons logging in the TP as well. I forgot to do that in the xtext repo myself

**Comment by cdietrich** [comment]
@LorenzoBettini  can you check if we need a follow up?

**Comment by LorenzoBettini** [comment]
@cdietrich see my comment on the domainmodel's TP

**Comment by cdietrich** [comment]
So we assume tycho magic will work ??

**Comment by LorenzoBettini** [comment]
I meant: if we want to be consistent, also the TP of domainmodel should be enhanced with the explicit specification of commons.logging

**Pull request merged**
