### PR TITLE
update for xtext.logging versionRange 0.0.0 in extraRequirements

### PR DESCRIPTION
**Pull request by LorenzoBettini**
see
https://github.com/eclipse/xtext/pull/2910
https://github.com/eclipse/xtext/issues/2909

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
@cdietrich the failure is the same, so I'm afraid I don't understand how to consume my fix merged on master...

**Comment by LorenzoBettini** [comment]
@cdietrich now the builds seem to fail due to a timeout in SWTBot tests

```
XtextNewProjectWizardTest.tearDown:53 » Timeout Timeout after: 10000 ms
```

**Comment by cdietrich** [comment]
is the the gradle problem we discussed last year?

**Comment by LorenzoBettini** [comment]
> is the the gradle problem we discussed last year?

I guess so

**Pull request merged**
